name: Build and Test Java Spring Boot Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          gradlew build

      - name: Test Report
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: SpringBoot Report               # Name of the folder
          path: target/site/serenity/           # Path to test results